# SLIDE (1) X-regression

In [5]:
import numpy as np
import pandas as pd
import sklearn
import warnings
warnings.filterwarnings('ignore')
from numpy.testing import assert_array_equal, assert_array_almost_equal, assert_equal, assert_almost_equal
from pandas.testing import assert_frame_equal

Необходимо найти наилучшие параметры для XGBRegression, обучить модель и вернуть ее. Данные из гита `Financial Distress.csv`.

Сам гридсерч или нативное исследование необходимо делать вне функции обработки, чтобы не получить TL.

# TASK

In [10]:
import pandas as pd
from sklearn.model_selection import train_test_split
from xgboost import XGBRegressor

def xreg(X_train, y_train):
    X = df.drop('Financial Distress', axis=1)
    y = df['Financial Distress']
    return XGBRegressor(
        base_score=0.5, 
        booster='gbtree',
        colsample_bylevel=1, 
        colsample_bynode=1,
        colsample_bytree=1,
        gamma=0,
#         gpu_id=-1,
#         importance_type='gain',
#         interaction_constraints='',
#         learning_rate=0.300000012,
#         max_delta_step=0,
#         max_depth=6,
#         min_child_weight=1,
#         missing=None,
#         monotone_constraints='()',
#         n_estimators=100,
#         n_jobs=12,
#         num_parallel_tree=1, 
#         random_state=0,
#         reg_alpha=0, 
#         reg_lambda=1,
#         scale_pos_weight=1, 
#         subsample=1,
#         tree_method='exact', 
#         validate_parameters=1,
#         verbosity=None
    ).fit(X,y)

In [23]:
import pandas as pd
from sklearn.model_selection import train_test_split
from xgboost import XGBRegressor


def xreg(X_train, y_train):
    fin ='Financial Distress'
    X, y= df.loc[:, df.columns != fin], df[fin]
    return XGBRegressor(
        base_score=0.5,
        booster='gbtree',
        colsample_bylevel=1,
        colsample_bynode=1,
        colsample_bytree=1,
        gamma=0,
        importance_type='gain',
        learning_rate=0.1,
        max_delta_step=0,
        max_depth=3,
        min_child_weight=1,
        n_estimators=100,
        n_jobs=1,
        objective='reg:linear',
        random_state=0,
        reg_alpha=0,
        reg_lambda=1,
        scale_pos_weight=1,
        subsample=1,
        verbosity=1,
        ).fit(X, y)


In [26]:
df.head()


Company  Time  Financial Distress      x1        x2       x3       x4  \
0        1     1            0.010636  1.2810  0.022934  0.87454  1.21640   
1        1     2           -0.455970  1.2700  0.006454  0.82067  1.00490   
2        1     3           -0.325390  1.0529 -0.059379  0.92242  0.72926   
3        1     4           -0.566570  1.1131 -0.015229  0.85888  0.80974   
4        2     1            1.357300  1.0623  0.107020  0.81460  0.83593   

         x5        x6       x7  ...      x74    x75     x76     x77   x78  \
0  0.060940  0.188270  0.52510  ...   85.437  27.07  26.102  16.000  16.0   
1 -0.014080  0.181040  0.62288  ...  107.090  31.31  30.194  17.000  16.0   
2  0.020476  0.044865  0.43292  ...  120.870  36.07  35.273  17.000  15.0   
3  0.076037  0.091033  0.67546  ...   54.806  39.80  38.377  17.167  16.0   
4  0.199960  0.047800  0.74200  ...   85.437  27.07  26.102  16.000  16.0   

   x79  x80       x81  x82  x83  
0  0.2   22  0.060390   30   49  
1  0.4   22  0.010636   31   50  
2 -0.2   22 -0.455970   32   51  
3  5.6   22 -0.325390   33   52  
4  0.2   29  1.251000    7   27  

[5 rows x 86 columns]

In [25]:

from sklearn.metrics import mean_squared_error as MSE
df= pd.read_csv('data/Financial Distress.csv')
df = df.dropna()
X = df.drop('Financial Distress', axis=1)
y = df['Financial Distress']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=17)

xgb_model = xreg(X_train, y_train)
assert type(xgb_model) == xgb.sklearn.XGBRegressor
y_pred = xgb_model.predict(X_test)

assert type(xgb_model) == xgb.sklearn.XGBRegressor
assert MSE(y_pred, y_test) < 3

[21:09:17] WARNING: /Users/travis/build/dmlc/xgboost/src/objective/regression_obj.cu:171: reg:linear is now deprecated in favor of reg:squarederror.


In [ ]:
df

# SLIDE (1) CatFeatures

Обучите модель классификации катбуста на предложенных данных и верните обученную модель. 

Воспользуйтесь встроенной обработкой категориальных признаков. Не забудьте обработать Nan значения.

Скрытых тестов нет, только один датасет `flyight_delays_train.csv` из гита 6 практики.

# TASK

In [88]:
import numpy as np 
import catboost
from catboost import CatBoostClassifier
def catfeatures(df: pd.DataFrame):
    fin ='dep_delayed_15min'
    X, y= df.loc[:, df.columns != fin], df[fin]
    
    y = y.apply(lambda x: 0 if x=='N' else 1)
    cat = X.dtypes == object
    X.loc[:, cat].fillna(-1, inplace=True)
            
    model = CatBoostClassifier()
    model.fit(X, y, range(len(cat)))
    
    return model

In [89]:
df = pd.read_csv('data/flight_delays_train.csv')
df_train = df[:1000]
model = catfeatures(df_train)
from sklearn.metrics import accuracy_score

assert type(model) == catboost.CatBoostClassifier

df_test = pd.read_csv('data/flight_catfeature_test.csv')
df_test = df_test.drop('Unnamed: 0', axis=1)
X_test = df_test.drop('dep_delayed_15min',axis=1)
y_test = df_test['dep_delayed_15min']

y_pred = model.predict(X_test)
assert accuracy_score(y_test, y_pred) > 0.80 
assert accuracy_score(y_test, y_pred) < 0.87 


Learning rate set to 0.010302
0:	learn: 0.6880647	total: 804us	remaining: 804ms
1:	learn: 0.6830621	total: 3.89ms	remaining: 1.94s
2:	learn: 0.6781825	total: 5.67ms	remaining: 1.89s
3:	learn: 0.6734352	total: 6.54ms	remaining: 1.63s
4:	learn: 0.6687738	total: 7.59ms	remaining: 1.51s
5:	learn: 0.6642379	total: 8.55ms	remaining: 1.42s
6:	learn: 0.6597950	total: 10.4ms	remaining: 1.48s
7:	learn: 0.6553847	total: 14.1ms	remaining: 1.75s
8:	learn: 0.6511244	total: 16.3ms	remaining: 1.79s
9:	learn: 0.6469634	total: 17.8ms	remaining: 1.76s
10:	learn: 0.6429135	total: 19ms	remaining: 1.71s
11:	learn: 0.6389341	total: 20.9ms	remaining: 1.72s
12:	learn: 0.6350308	total: 23.1ms	remaining: 1.75s
13:	learn: 0.6311675	total: 25.5ms	remaining: 1.8s
14:	learn: 0.6274755	total: 26.9ms	remaining: 1.77s
15:	learn: 0.6237818	total: 29.1ms	remaining: 1.79s
16:	learn: 0.6202563	total: 30.2ms	remaining: 1.75s
17:	learn: 0.6166788	total: 32.4ms	remaining: 1.77s
18:	learn: 0.6133159	total: 33.9ms	remaining: 1.

179:	learn: 0.4535228	total: 372ms	remaining: 1.69s
180:	learn: 0.4534409	total: 373ms	remaining: 1.69s
181:	learn: 0.4533607	total: 374ms	remaining: 1.68s
182:	learn: 0.4530210	total: 377ms	remaining: 1.68s
183:	learn: 0.4524465	total: 381ms	remaining: 1.69s
184:	learn: 0.4523473	total: 382ms	remaining: 1.68s
185:	learn: 0.4520311	total: 386ms	remaining: 1.69s
186:	learn: 0.4516526	total: 390ms	remaining: 1.7s
187:	learn: 0.4514413	total: 396ms	remaining: 1.71s
188:	learn: 0.4510695	total: 400ms	remaining: 1.72s
189:	learn: 0.4507154	total: 404ms	remaining: 1.72s
190:	learn: 0.4503920	total: 408ms	remaining: 1.73s
191:	learn: 0.4500736	total: 413ms	remaining: 1.74s
192:	learn: 0.4496950	total: 418ms	remaining: 1.75s
193:	learn: 0.4496354	total: 419ms	remaining: 1.74s
194:	learn: 0.4493384	total: 423ms	remaining: 1.75s
195:	learn: 0.4491667	total: 426ms	remaining: 1.75s
196:	learn: 0.4488887	total: 429ms	remaining: 1.75s
197:	learn: 0.4483192	total: 434ms	remaining: 1.76s
198:	learn: 0

365:	learn: 0.4144385	total: 944ms	remaining: 1.64s
366:	learn: 0.4143761	total: 950ms	remaining: 1.64s
367:	learn: 0.4138900	total: 954ms	remaining: 1.64s
368:	learn: 0.4138132	total: 958ms	remaining: 1.64s
369:	learn: 0.4133920	total: 961ms	remaining: 1.64s
370:	learn: 0.4129866	total: 965ms	remaining: 1.64s
371:	learn: 0.4128019	total: 969ms	remaining: 1.64s
372:	learn: 0.4126329	total: 973ms	remaining: 1.64s
373:	learn: 0.4125121	total: 976ms	remaining: 1.63s
374:	learn: 0.4122464	total: 980ms	remaining: 1.63s
375:	learn: 0.4121048	total: 983ms	remaining: 1.63s
376:	learn: 0.4118869	total: 987ms	remaining: 1.63s
377:	learn: 0.4116563	total: 991ms	remaining: 1.63s
378:	learn: 0.4114194	total: 995ms	remaining: 1.63s
379:	learn: 0.4112333	total: 999ms	remaining: 1.63s
380:	learn: 0.4111556	total: 1s	remaining: 1.63s
381:	learn: 0.4109366	total: 1s	remaining: 1.63s
382:	learn: 0.4106849	total: 1.01s	remaining: 1.62s
383:	learn: 0.4102635	total: 1.01s	remaining: 1.62s
384:	learn: 0.4100

566:	learn: 0.3743956	total: 1.67s	remaining: 1.27s
567:	learn: 0.3743296	total: 1.67s	remaining: 1.27s
568:	learn: 0.3741230	total: 1.68s	remaining: 1.27s
569:	learn: 0.3739624	total: 1.68s	remaining: 1.27s
570:	learn: 0.3734807	total: 1.68s	remaining: 1.26s
571:	learn: 0.3732724	total: 1.69s	remaining: 1.26s
572:	learn: 0.3732347	total: 1.69s	remaining: 1.26s
573:	learn: 0.3729264	total: 1.7s	remaining: 1.26s
574:	learn: 0.3725161	total: 1.7s	remaining: 1.25s
575:	learn: 0.3724524	total: 1.7s	remaining: 1.25s
576:	learn: 0.3721093	total: 1.71s	remaining: 1.25s
577:	learn: 0.3719823	total: 1.71s	remaining: 1.25s
578:	learn: 0.3718449	total: 1.71s	remaining: 1.25s
579:	learn: 0.3717876	total: 1.72s	remaining: 1.24s
580:	learn: 0.3716340	total: 1.72s	remaining: 1.24s
581:	learn: 0.3712515	total: 1.73s	remaining: 1.24s
582:	learn: 0.3712193	total: 1.73s	remaining: 1.24s
583:	learn: 0.3709559	total: 1.73s	remaining: 1.23s
584:	learn: 0.3708544	total: 1.74s	remaining: 1.23s
585:	learn: 0.3

726:	learn: 0.3445773	total: 2.24s	remaining: 841ms
727:	learn: 0.3442817	total: 2.24s	remaining: 838ms
728:	learn: 0.3440869	total: 2.25s	remaining: 836ms
729:	learn: 0.3440197	total: 2.25s	remaining: 833ms
730:	learn: 0.3438502	total: 2.26s	remaining: 831ms
731:	learn: 0.3437588	total: 2.26s	remaining: 828ms
732:	learn: 0.3432976	total: 2.27s	remaining: 826ms
733:	learn: 0.3431454	total: 2.27s	remaining: 823ms
734:	learn: 0.3429330	total: 2.27s	remaining: 820ms
735:	learn: 0.3428549	total: 2.28s	remaining: 817ms
736:	learn: 0.3425778	total: 2.28s	remaining: 815ms
737:	learn: 0.3422527	total: 2.29s	remaining: 812ms
738:	learn: 0.3422231	total: 2.29s	remaining: 809ms
739:	learn: 0.3419509	total: 2.29s	remaining: 806ms
740:	learn: 0.3415081	total: 2.3s	remaining: 803ms
741:	learn: 0.3412711	total: 2.3s	remaining: 801ms
742:	learn: 0.3408681	total: 2.31s	remaining: 798ms
743:	learn: 0.3406252	total: 2.31s	remaining: 795ms
744:	learn: 0.3406072	total: 2.31s	remaining: 792ms
745:	learn: 0.

921:	learn: 0.3100353	total: 3.01s	remaining: 255ms
922:	learn: 0.3098766	total: 3.02s	remaining: 252ms
923:	learn: 0.3097479	total: 3.02s	remaining: 249ms
924:	learn: 0.3095894	total: 3.03s	remaining: 245ms
925:	learn: 0.3095299	total: 3.03s	remaining: 242ms
926:	learn: 0.3092529	total: 3.04s	remaining: 239ms
927:	learn: 0.3091437	total: 3.04s	remaining: 236ms
928:	learn: 0.3090363	total: 3.04s	remaining: 233ms
929:	learn: 0.3088180	total: 3.05s	remaining: 229ms
930:	learn: 0.3087167	total: 3.05s	remaining: 226ms
931:	learn: 0.3085605	total: 3.06s	remaining: 223ms
932:	learn: 0.3083924	total: 3.06s	remaining: 220ms
933:	learn: 0.3081947	total: 3.06s	remaining: 217ms
934:	learn: 0.3080036	total: 3.07s	remaining: 213ms
935:	learn: 0.3079575	total: 3.07s	remaining: 210ms
936:	learn: 0.3078174	total: 3.08s	remaining: 207ms
937:	learn: 0.3076379	total: 3.08s	remaining: 204ms
938:	learn: 0.3074109	total: 3.08s	remaining: 200ms
939:	learn: 0.3071270	total: 3.09s	remaining: 197ms
940:	learn: 

In [59]:
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 9 columns):
 #   Column             Non-Null Count   Dtype 
---  ------             --------------   ----- 
 0   Month              100000 non-null  object
 1   DayofMonth         100000 non-null  object
 2   DayOfWeek          100000 non-null  object
 3   DepTime            100000 non-null  int64 
 4   UniqueCarrier      100000 non-null  object
 5   Origin             100000 non-null  object
 6   Dest               100000 non-null  object
 7   Distance           100000 non-null  int64 
 8   dep_delayed_15min  100000 non-null  object
dtypes: int64(2), object(7)
memory usage: 6.9+ MB


In [50]:
    fin ='dep_delayed_15min'
    X, y= df.loc[:, df.columns != fin], df[fin]
    
    y = y.apply(lambda x: 0 if x=='N' else 1)
    is_cat = (X.dtypes != float)

In [69]:
is_cat


Month            True
DayofMonth       True
DayOfWeek        True
DepTime          True
UniqueCarrier    True
Origin           True
Dest             True
Distance         True
dtype: bool

# SLIDE (1) LightGBM

Вашем вниманию представляется прокаченный градиентный бустинг `LightGBM`. Разобраться в нем вам предлагается самостоятельно, например по [статье на хабре](https://habr.com/ru/company/skillfactory/blog/530594/). 

А в задачке, вам необходимо (опять...) найти наилучшие параметры для LGBMRegressor, обучить модель и вернуть ее. Данные из гита `Financial Distress.csv`.

Сам гридсерч или нативное исследование необходимо делать вне функции обработки, чтобы не получить TL.

# TASK

In [102]:
import lightgbm
from lightgbm import LGBMRegressor

def lgbmreg(X_train, y_train):
    return LGBMRegressor(
#         max_depth=5, 
        learning_rate = .01
    ).fit(X_train, y_train)

In [103]:
df = pd.read_csv('data/Financial Distress.csv')

X = df.drop('Financial Distress', axis=1)
y = df['Financial Distress']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=17)

lgbm_model = lgbmreg(X_train, y_train)
y_pred = lgbm_model.predict(X_test)

assert type(lgbm_model) == lightgbm.sklearn.LGBMRegressor

assert MSE(y_pred, y_test) < 1.2

# SLIDE (2) Производные для регрессии

Окей, в лекции было очень много страшных формул, теперь можно осознать зачем это нужно.

Пусть мы хотим бустить регрессию со стандартной функцией потерь $MSE$:

$$\mathcal{L}(a, x,y) = (a(x_i) - y_i)^2$$

Необходимо найти через взятие производных:

1. Константный вектор $[f_0]_{i=1}^{N}$
$$f_0(x) = \arg\min_{ c\in \mathbb{R}} \sum_{i=1}^n \mathcal{L}(c, x_i, y_i)$$ 

2. Градиенты функции потерь
$$g_{i}^{t} = -\Big[\frac{\partial \mathcal{L}(f_t, x_i, y_i)}{\partial f_t(x_i)}\Big]_{i=1}^N$$

3. Коэффициенты при композиции 
$$\alpha_{t + 1} = \arg\min_\alpha \sum_{i=1}^N \mathcal{L}(f_{t} + \alpha b_{t+1}, x_i, y_i)$$

### Sample 1
#### Input:
```python
y = np.array([1, 2, 3])
f = np.array([2, 2, 2])
b = np.array([0, 2, 4])
```
#### Output:
```python
f_0 = 2.0
g = [-2, 0,  2] 
alpha = 0.2

```

# TASK

In [36]:
import numpy as np
from numpy.testing import assert_array_almost_equal

In [157]:
def init(y_i: np.array) -> float:
    v, k = min([[np.sum(np.square(c/10-y_i)), c/10] for c in range(-100, 100, 1)], key=lambda l: l[0])

    return k

def grad(a: np.array, y: np.array) -> np.array:
    return dz(np.square(a-y), y)

def dz(x,dx):
    print(x)
    x__ = np.insert(x.copy(), -1, x[-1])
    x_ = np.insert(x.copy(), 0, x[0])
    print(x_, x__, dx, np.diff(x_ - x__), np.diff(x_ - x__) / dx)
    return np.diff(x_ - x__) / dx

def alpha(f :np.array, b: np.array, y: np.array) -> float:
    v, k = min([[np.sum(np.square((f-al/100*b)-y)), al/100] for al in range(-200, 200, 1)], key=lambda l: l[0])
    return -k

In [158]:
y = np.array([1, 2, 3])
f = np.array([2, 2, 2])
b = np.array([0, 2, 4])

f_0 = init(y)
g = grad(f,y)
al = alpha(f,b,y)

assert np.abs(f_0 - 2.0)   < 1e-9
assert_array_almost_equal(g, np.array([-2, 0, 2]))
assert np.abs(al - (0.2)) < 1e-9, al
######################################################
y = np.arange(20)
f = np.ones(20) * 10
b = np.arange(20) - 1

f_0 = init(y)
g = grad(f,y)
al = alpha(f,b,y)


assert np.abs(f_0 - 9.5)   < 1e-2, f_0
assert_array_almost_equal(g, np.arange(-20,20, 2))
assert np.abs(al - (0.2748)) < 1e-2, al


[1 0 1]
[1 1 0 1] [1 0 1 1] [1 2 3] [ 1 -2  1] [ 1.         -1.          0.33333333]


AssertionError: 
Arrays are not almost equal to 6 decimals

Mismatched elements: 3 / 3 (100%)
Max absolute difference: 3.
Max relative difference: 1.5
 x: array([ 1.      , -1.      ,  0.333333])
 y: array([-2,  0,  2])

In [141]:
np.insert(y, 0, 7)

array([7, 1, 2, 3])

In [31]:
min([[np.sum(np.square(c-y)), c] for c in range(-10, 10, 1)], key=lambda l: l[0])


[2, 2]

In [28]:
range(-10,10,1)

range(-10, 10)

In [14]:
np.linalg.norm(1-y,axis=0)

2.23606797749979

In [15]:
y

array([1, 2, 3])

In [16]:
f

array([2, 2, 2])

In [113]:
b

array([0, 2, 4])

# SLIDE (2) GradientBoosting

Реализуйте градиентный бустинг на решающих деревьях для регрессии с логгированием.Верните модель, которая будет хранить в себе `n_estimatos` обученных деревьев и коэффициенты, чтобы с их помощью потом найти результат предсказания.

Также необходимо реализовать логгирование в течение обучения.

* `self.estimators` - лист c деревьями
* `self.alpha` - лист с коэффициентами альфа
* `self.f_list` - лист со значениями комбинаций алгоритма $f_T(x_i) = f_0(x_i) + \sum_{t=1}^{T}\alpha_tb_t(x_i)$
* `self.g_list` - лист с векторами градиентов на каждой итерации $g_{i}^{t} = -\Big[\frac{\partial \mathcal{L}(f_t, x_i, y_i)}{\partial f_t(x_i)}\Big]_{i=1}^N$
* `self.b_list` - лист со значениями базового обучаемого дерева на тренировочной выборке на каждой итерации 

Примечания:

* Обрывать алгоритм не нужно, необходимо обучить все деревья.
* Начальный константный вектор из $f_0$ логгировать не нужно, однако не забудьте его добавить в `predict` c нужным количеством объектов!

### Sample 1
#### Input:
```python
n_estimators = 2
max_depth=3
X_train = np.array([[0], [1], [2], [3], [4]])
y_train = np.array([0, 2, 4, 2, 0])
X_test  = np.array([[1.2], [2.3]])
y_test  = np.array([2.2, 3.7])
```
#### Output:
```python
y_test_pred = [2, 4]

model.f_list = [array([0.0, 2.0, 3.0, 3.0, 0.0]), 
                array([0.0, 2.0, 4.0, 2.0, 0.0])]

model.g_list = [array([-3.2,  0.8, 4.8, 0.8, -3.2]), 
                array([ 0.0,  0.0, 2.0,-2.0,  0.0])]

model.b_list = [array([-3.2, 0.8, 2.8,  2.8, -3.2]), 
                array([ 0.0, 0.0, 2.0, -2.0,  0.0])]
```

# TASK

In [165]:
import numpy as np
from sklearn.tree import DecisionTreeRegressor as DTR
from sklearn.metrics import mean_squared_error


def loss_gradient(y, y_hat): 
    return -(y-y_hat)

def compute_loss(y, y_hat): 
    return ((y - y_hat) ** 2) / 2


class MyGradBoost():
    def __init__(self, n_estimators=10, max_depth=3):
        self.n_estimators = n_estimators
        self.max_depth = max_depth
        self.estimators_ = np.array([DTR(max_depth=self.max_depth) for _ in range(n_estimators)])
        self.alpha = []
        self.f_list = []
        self.b_list = []
        self.g_list = []
        
        self.f0 = None
        
    def fit(self, X_train: np.array, y_train: np.array):
        f0 = self.gradient_boost_mse(X_train, y_train, self.n_estimators, .1)
        self.f0 = f0
        return self
        
    def predict(self, X_test) -> np.array:
        y_pred = self.gradient_boost_mse_predict(self.estimators_, self.f0, X_test, 0.1)
        return y_pred
    
    def gradient_boost_mse(self, X, y, M, learning_rate): 
        y_hat = np.array([y.mean()]*len(y)) 
        f0 = y_hat 
        print(compute_loss(y, y_hat).mean()) 
        for i in range(M): 
            residuals = -loss_gradient(y, y_hat)
            self.g_list.append(residuals)
            print(len( self.estimators_))
            regressor = self.estimators_[i]
            regressor.fit(X, residuals)
            predictions = regressor.predict(X) 
            self.b_list.append(predictions)
            y_hat = y_hat + learning_rate * predictions
            self.f_list.append(y_hat)
            print(compute_loss(y, y_hat).mean()) 
        return f0
    
    def gradient_boost_mse_predict(self, regressors, f0, X, learning_rate):
        y_hat = np.array([f0[0]]*len(X)) 
        for regressor in regressors: 
            y_hat = y_hat + learning_rate * regressor.predict(X) 
        return y_hat
    
    def score(self, X_test, y_test)-> np.array:
        return mean_squared_error(self.predict(X_test), y_test)

In [168]:
n_estimators = 2
max_depth=3
X_train = np.array([[0], [1], [2], [3], [4]])
y_train = np.array([0, 2, 4, 2, 0])
X_test  = np.array([[1.2], [2.3]])
y_test  = np.array([2.2, 3.7])

model = MyGradBoost(n_estimators=n_estimators, max_depth=max_depth).fit(X_train, y_train)
assert model.score(X_test, y_test) < 0.2,  model.score(X_test, y_test)
######################################################
n_train, n_test, noise = 150, 1000, 0.1
# Generate data
def f(x):
    x = x.ravel()
    return np.exp(-x ** 2) + 1.5 * np.exp(-(x - 2) ** 2)

def generate(n_samples, noise):
    X = np.random.rand(n_samples) * 10 - 5
    X = np.sort(X).ravel()
    y = np.exp(-X ** 2) + 1.5 * np.exp(-(X - 2) ** 2)\
        + np.random.normal(0.0, noise, n_samples)
    X = X.reshape((n_samples, 1))

    return X, y

X_train, y_train = generate(n_samples=n_train, noise=noise)
X_test, y_test = generate(n_samples=n_test, noise=noise)


model = MyGradBoost().fit(X_train, y_train)

assert model.score(X_test, y_test) < 0.02 ,  model.score(X_test, y_test)


model = MyGradBoost(n_estimators=100, 
                    max_depth=1).fit(X_train, y_train)

assert model.score(X_test, y_test) < 0.017


1.12
2
0.9451999999999998
2
0.799907


AssertionError: 1.7646410000000003

## Useful graphs

In [ ]:
def predict_and_plot(model, X_test, y_test, title):
    y_predict = model.predict(X_test)

    plt.plot(X_test, f(X_test), "b")
    plt.scatter(X_train, y_train, c="b", s=20)
    plt.plot(X_test, y_predict, "g", lw=2)
    plt.xlim([-5, 5])
    plt.title("{} Loss: {:2f}".format(title, model.score(X_test, y_test)))
    plt.grid()



model = MyGradBoost(n_estimators=30, 
                    max_depth=1).fit(X_train, y_train)

ind =  [1,3,5,10,15,30]

# GradientBoostingRegressor
plt.plot(X_test, f(X_test), "b")
plt.scatter(X_train, y_train, c="b", s=20)
n_est = [1,3,5,10,15,30]
f = np.array(model.f_list)
for i, n in enumerate(n_est):
    colors = ['g', 'r', 'c', 'm', 'y', 'k']
    plt.plot(X_train, f[n-1], color=colors[i], label="tree count={}".format(n))

plt.xlim([-5, 5])   
plt.legend()
plt.grid()
plt.show()

# SLIDE (1) AdaBoost step

Реализуйте одну итерацию алгоритма AdaBoost:

1. Обучите дерево $b$ на $X_{train}$ и верните $y_{pred}$

2. Найдите среднюю взвешанную ошибку
$$error = Q(b_t, X, y) = \frac{1}{N}\sum_{i=1}^{N}w_i^{(t-1)}[y_i \neq b_t(x)]$$

3. Найдите коэффициент $\alpha$ (для корректного выполнения добавим $eps$)
$$\alpha = \frac{1}{2}\ln\Big(\frac{1-error + eps}{error + eps}\Big)$$

4. Найдите новые веса:
$$w_i^{new} = w_iexp\Big(-\alpha y_i b(x_i)\Big)$$
$$\tilde{w}_i^{new} = \frac{w_i^{new}}{\sum_{i=1}^{N}w_i^{new}}$$

### Sample 1
#### Input:
```python
X_train = np.array([[0, 0], [4, 0], [0, 4], [4, 4]])
y_train = np.array([-1, -1, -1, 1])
```
#### Output:
```python
y_pred =  [-1 -1 -1 -1] 
error = 0.056 
alpha = 1.417 
new_weights = [0.05882403 0.41176819 0.02941201 0.49999576]
```

# TASK

In [184]:
def m(w):
    return w / np.sum(w)

def get_err(cond, weights, rep=0):
    return np.sum(np.where(cond, weights, rep))

def boost_step(estimator, weights, X_train, y_train, eps = 1e-6):
    estimator.fit(X_train, y_train)
    y_pred = estimator.predict(X_train)
    weights = m(weights)
    error = get_err(y_train != y_pred, weights)
    ee = error + eps
    d = (1 - ee) / (ee)
    alpha = 1/2 * np.log(d)
    g = weights * np.exp(-alpha * y_pred * y_train)
    new_weights = m(g)
    return y_pred, error, alpha, new_weights

In [185]:
from numpy.testing import assert_array_almost_equal
######################################################
X_train = np.array([[0, 0], [4, 0], [0, 4], [4, 4]])
y_train = np.array([-1, -1, -1, 1])

estimator = DTC(max_depth=1, random_state=4)
sample_weights = [0.1, 0.7, 0.05, 0.05]
y_pred, error, alpha, new_weights = boost_step(estimator, sample_weights, X_train, y_train)
assert_array_almost_equal(y_pred, np.array([-1, -1, -1, -1])) 
assert np.abs(error - 0.056) < 1e-2 
assert np.abs(alpha - 1.417) < 1e-2 
assert_array_almost_equal(new_weights, np.array([0.05882403, 0.41176819, 0.02941201, 0.49999576]))
######################################################
X_train = np.array([[0, 0], [3, 3], [5, 5], [10, 10]])
y_train = np.array([-1, -1, 1, 1])
estimator = DTC(max_depth=1, random_state=6)
sample_weights = [0.1, 0.7, 0.05, 0.05]

y_pred, error, alpha, new_weights = boost_step(estimator, sample_weights, X_train, y_train)


assert_array_almost_equal(y_pred, np.array([-1, -1, 1, 1])) 
assert np.abs(error - 0.0) < 1e-2 
assert np.abs(alpha - 6.907) < 1e-2 
assert_array_almost_equal(new_weights, np.array([0.11111111, 0.77777778, 0.05555556, 0.05555556]))


# SLIDE (1) AdaBoost classifier

Реализуйте AdaBoost для бинарной классификации на деревьях высоты 1. Верните модель, которая будет хранить в себе `n_estimatos` обученных деревьев и коэффициенты, чтобы с их помощью потом найти результат предсказания.

Также необходимо реализовать логгирование в течение обучения.

* `self.sample_weights_list` - лист с весами объектов на каждой итерации
* `self.y_pred_list` - лист с предсказанием каждого следующего дерева (не комбинации)
* `self.error_list` - лист с ошибками

Примечания:

* Обрывать алгоритм не нужно, необходимо обучить все деревья.
* Начальные веса логгировать не нужно
* `predict_proba` реализовывать не нужно

### Sample 1
#### Input:
```python
n_estimators = 2
X_train = np.array([[0, 0], [4, 0], [0, 4], [4, 4]])
y_train = np.array([-1, -1, -1, 1])
X_test  = np.array([[1, 0], [5, 5]])
y_test  = np.array([-1, 1])
```
#### Output:
```python
y_test_pred = [0, 1]

model.sample_weight = [array([0.167, 0.167, 0.167, 0.5]), 
                       array([ 0.1,  0.5,  0.1, 0.3])]
model.y_pred = [array([-1, -1, -1, -1]),
                array([-1,  1, -1,  1])]

model.alpha = [0.25, 0.167]
```


# TASK

In [202]:
import numpy as np
from sklearn.tree import DecisionTreeClassifier as DTC

class MyAdaBoost():
    def __init__(self, n_estimators=10):
        self.estimators_ = np.array([DTC(max_depth=1) for _ in range(n_estimators)])
        self.alpha = []
        self.sample_weights_list = []
        self.y_pred_list = []
        self.error_list = []
        
    def fit(self, X_train: np.array, y_train: np.array):
        ### ╰( ͡° ͜ʖ ͡° )つ──☆*:・ﾟ
        return self
        
    def predict(self, X_test) -> np.array:
        ### ╰( ͡° ͜ʖ ͡° )つ──☆*:・ﾟ
        pass


In [54]:
######################################################
X_train = np.array([[0, 0], [4, 0], [0, 4], [4, 4]])
y_train = np.array([-1, -1, -1, 1])
X_test  = np.array([[1, 0], [5, 5]])
y_test  = np.array([-1, 1])

model = MyAdaBoost(n_estimators = 2).fit(X_train, y_train)

y_pred_my = model.predict(X_test)

assert_array_almost_equal(y_pred_my, np.array([-1, 1]))

######################################################
X_train = np.array([[0, 0], [4, 4], [5, 5], [10, 10]])
y_train = np.array([-1, -1, 1, 1])
X_test  = np.array([[3, 3], [6, 6]])
y_test  = np.array([-1, 1])

model = MyAdaBoost(n_estimators = 2).fit(X_train, y_train)

y_pred_my = model.predict(X_test)

assert_array_almost_equal(y_pred_my, np.array([-1, 1]))
######################################################
num_samples = 1000
theta = np.linspace(0, 2*np.pi, num_samples)
r1 = 1
r2 = 2

rng = np.random.RandomState(1)

circle = np.hstack([np.cos(theta).reshape((-1, 1)) + (rng.randn(num_samples)[:,np.newaxis] / 8), 
                    np.sin(theta).reshape((-1, 1)) + (rng.randn(num_samples)[:,np.newaxis] / 8)])
lil = r1 * circle
big = r2 * circle
X = np.vstack([lil, big])
y = np.hstack([(-1) * np.ones(num_samples), np.ones(num_samples)])




X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                    test_size=0.3,
                                                    random_state=123,
                                                    shuffle=True)

y_test = y_test.astype('int')


y_pred_my = MyAdaBoost(n_estimators = 20).fit(X_train, y_train).predict(X_test)

assert accuracy_score(y_pred_my, y_test) > 0.95

## Useful graphs 

In [ ]:
#Toy Dataset
x1 = np.array([.1,.2,.4,.8, .8, .05,.08,.12,.33,.55,.66,.77,.88,.2,.3,.4,.5,.6,.25,.3,.5,.7,.6])
x2 = np.array([.2,.65,.7,.6, .3,.1,.4,.66,.77,.65,.68,.55,.44,.1,.3,.4,.3,.15,.15,.5,.55,.2,.4])
y = np.array([1,1,1,1,1,1,1,1,1,1,1,1,1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1])
X = np.vstack((x1,x2)).T

boost = MyAdaBoost(n_estimators = 20).fit(X, y)
sample_weight_list = np.array(boost.sample_weight_list)
estimator_list = np.array(boost.estimators_)
alpha = np.array(boost.alpha)

fig = plt.figure(figsize = (14,14))
for m in range(0,9):
    fig.add_subplot(3,3,m+1)
    s_weights = (sample_weight_list[m,:] / sample_weight_list[m,:].sum() ) * 40
    plot_decision_boundary(estimator_list[m], X, y, N = 50, scatter_weights =s_weights )
    plt.title('Estimator decision boundary, m = {}'.format(m))
print('Well Done!')

# SLIDE (1) Stacking

**Стэкинг** - 3-ий способ комбинирования алгоритмов, кроме бэггинга и бустинга. Он не часто используется, но его идея крайне полезная: `обучение на мета-признаках`.

1. Разобъем нашу обучающую выборку на 2 части: базовую и дополнительную.
2. Возьмем $N$ базовых алгоритмов и обучим их на **базовой части** разбив на $N$ фолдов. (Разбили на $N$ частей и обучаем алгоритм на всех частях кроме одной, как на кросс-валидации)
3. Каждым из обученных базовых алгоритмов предскажем значение для **дополнительной** части выборки.
4. Соберем **мета-выборку**, состоящую из предсказаний базовых алгоритмов на **доп выборе**. Пример: пусть для объекта $x_i$ базовые алгоритмы выдали $(y_i^1 = 1, y_i^2 = 0, y_i^3 = 1)$. Тогда признаками объекта в **мета-выборке** будет вектор $1, 0, 1$.
5. Обучим **мета-алгоритм** на **мета-выборке**. И получим готовую модель.
6. Чтобы получить результат на тестовой, теперь нужно сделать предсказания базовыми алгоритмами, собрать **мета-выборку** и сделать предсказания на **мета-алгоритме**.

Реализуйте стекинг классификацию на **деревьях решений**. Валидация проводится на датасете `forest_train.csv` из папки в гите в 6 практике.

# TASK

In [ ]:
import numpy as np
from sklearn.tree import DecisionTreeClassifier as DTC

class Stacking():
    def __init__(self, n_estimators=5, max_depth=5):
        self.max_depth_ = max_depth
        self.n_estimators_ = n_estimators
        self.estimators_ = [DTC(max_depth=self.max_depth_) for _ in range(self.n_estimators_)]
        self.meta_estimator_ = DTC(max_depth=self.max_depth_)
        
    def fit(self, X: np.array, y: np.array): 
        ### ╰( ͡° ͜ʖ ͡° )つ──☆*:・ﾟ
        return self
        
    def predict(self, X_test) -> np.array:
        ### ╰( ͡° ͜ʖ ͡° )つ──☆*:・ﾟ
        return y_pred

In [60]:
import sklearn
df = pd.read_csv('data/forest_train.csv')

X = df.drop(columns=['Cover_Type', 'Id']).reset_index(drop=True)
y = df['Cover_Type']
X_train, X_test, y_train, y_test = train_test_split(X.values, y.values, train_size=0.3)

model = Stacking(max_depth=10, n_estimators=3).fit(X_train, y_train)

assert type(model.meta_estimator_) == sklearn.tree.DecisionTreeClassifier

y_pred = model.predict(X_test)
y_pred1 = model.estimators_[0].predict(X_test)
y_pred2 = model.estimators_[1].predict(X_test)
y_pred3 = model.estimators_[2].predict(X_test)

assert accuracy_score(y_pred, y_test) > 0.67

assert accuracy_score(y_pred1, y_test) < accuracy_score(y_pred, y_test)
assert accuracy_score(y_pred2, y_test) < accuracy_score(y_pred, y_test)
assert accuracy_score(y_pred3, y_test) < accuracy_score(y_pred, y_test)